pipeline {
    agent any    
    
    stages {
        
        stage ('Compile Stage') {            
        
        	steps {
                withMaven(maven : 'Maven') {
                    bat 'mvn -f JenkinsJob/pom.xml clean compile'
               	}
            }
        }
        
        stage ('Testing Stage') {            
        
        	steps {
                withMaven(maven : 'Maven') {
                    bat 'mvn -f JenkinsJob/pom.xml test'
                }
            }
        }
        stage ('Deployment Stage') {
            steps {
                withMaven(maven : 'Maven') {
                    bat 'mvn -f JenkinsJob/pom.xml deploy'
                }
            }
        }
    }
}